// This file was automatically generated by VS extension Windows Machine Learning Code Generator v3
// from model file emotion_ferplus.onnx
// Warning: This file may get overwritten if you add add an onnx file with the same name
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Windows.Media;
using Windows.Storage;
using Windows.Storage.Streams;
using Windows.AI.MachineLearning;
namespace AlarmML
{
    
    public sealed class emotion_ferplusInput
    {
        public TensorFloat Input338; // shape(1,1,64,64)
    }
    
    public sealed class emotion_ferplusOutput
    {
        public TensorFloat Plus692_Output_0; // shape(1,8)
    }
    
    public sealed class emotion_ferplusModel
    {
        private LearningModel model;
        private LearningModelSession session;
        private LearningModelBinding binding;
        public static async Task<emotion_ferplusModel> CreateFromStreamAsync(IRandomAccessStreamReference stream)
        {
            emotion_ferplusModel learningModel = new emotion_ferplusModel();
            learningModel.model = await LearningModel.LoadFromStreamAsync(stream);
            learningModel.session = new LearningModelSession(learningModel.model);
            learningModel.binding = new LearningModelBinding(learningModel.session);
            return learningModel;
        }
        public async Task<emotion_ferplusOutput> EvaluateAsync(emotion_ferplusInput input)
        {
            binding.Bind("Input338", input.Input338);
            var result = await session.EvaluateAsync(binding, "0");
            var output = new emotion_ferplusOutput();
            output.Plus692_Output_0 = result.Outputs["Plus692_Output_0"] as TensorFloat;
            return output;
        }
    }
}

